name: Deploy AWS infra

on:
    push:
        branches:
            - master
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Setup Python
              uses: actions/setup-python@v2
              with: 
                python-version: "3.x"

            - name: Install Dependency
              run: |
                python -m venv venv
                source venv/bin/activate
                pip install pulumi pulumi-aws

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v2
              with: 
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ap-southeast-1

            - name: Set public key environment variable
              run: echo "PUBLIC_KEY=${{ secrets.PUBLIC_KEY }}" >> $GITHUB_ENV
                
            - name: Pulumi login
              env:
                PULUMI_ACCESS_TOKEN: ${{secrets.PULUMI_ACCESS_TOKEN}}
              run:
                pulumi login

            - name: Pulumi stack select
              run:
                pulumi stack select asadlive84/code/dev
            
            - name: Pulumi up
              run:
                pulumi up --yes